// Builds the Rust core to wasm32-wasip1 and stages it for Vite.
//
// The output is a plain WASI reactor module, not a wasm-bindgen bundle: the
// module is instantiated against @bjorn3/browser_wasi_shim inside a worker, so
// the only artefact the app needs is the .wasm itself.

import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const TARGET = 'wasm32-wasip1';
// `release-size` swaps opt-level 3 for "z"; see wasm/Cargo.toml.
const profile = process.env.WASM_PROFILE === 'size' ? 'release-size' : 'release';

execFileSync('node', [join(root, 'scripts', 'prepare-vendor.mjs')], { stdio: 'inherit' });

console.log(`[wasm] cargo build --profile ${profile} --target ${TARGET}`);
execFileSync('cargo', ['build', '--profile', profile, '--target', TARGET], {
  cwd: join(root, 'wasm'),
  stdio: 'inherit',
});

const artefact = join(root, 'wasm', 'target', TARGET, profile, 'wsi_core.wasm');
const outDir = join(root, 'public', 'wasm');
mkdirSync(outDir, { recursive: true });
copyFileSync(artefact, join(outDir, 'wsi_core.wasm'));

const bytes = statSync(artefact).size;
console.log(`[wasm] staged public/wasm/wsi_core.wasm (${(bytes / 1024 / 1024).toFixed(1)} MB)`);

// The accept-list is derived from the crate rather than hand-maintained, but
// asking the 8.5 MB module for it at runtime would mean compiling WASM just to
// render a file picker. It is extracted once here instead.
const { WASI } = await import('node:wasi');
const wasi = new WASI({ version: 'preview1', preopens: {} });
const probeModule = await WebAssembly.compile(await readFile(artefact));
const probe = await WebAssembly.instantiate(probeModule, wasi.getImportObject());
wasi.initialize(probe);

const api = probe.exports;
const packed = BigInt.asUintN(64, api.bf_supported_extensions_json());
const ptr = Number(packed >> 32n);
const len = Number(packed & 0xffffffffn);
if (ptr === 0) throw new Error('bf_supported_extensions_json failed');
const json = new TextDecoder().decode(new Uint8Array(api.memory.buffer, ptr, len).slice());
api.bf_free(ptr, len);

const extensions = JSON.parse(json);
const generated = join(root, 'src', 'generated', 'supported-extensions.ts');
writeFileSync(
  generated,
  `// Generated by scripts/build-wasm.mjs. Do not edit.\n` +
    `//\n` +
    `// Every extension that at least one bioformats reader claims via its own\n` +
    `// is_this_type_by_name predicate, so this tracks the crate's real coverage.\n\n` +
    `export const SUPPORTED_EXTENSIONS = ${JSON.stringify(extensions, null, 2)} as const;\n`,
);
console.log(`[wasm] wrote ${String(extensions.length)} supported extensions`);
